name: workflow
on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'

    - name: Install dependencies
      run: |
        brew install swiftlint

    - name: Set up Environment Variables
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" > .env

    - name: Build and Test
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        xcodebuild -scheme MyScheme -sdk iphonesimulator clean build
        xcodebuild test -scheme MyScheme -sdk iphonesimulator
        echo "API Key: $API_KEY"
