name: workflow
on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: API Key
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        echo "API Key: $API_KEY"
